import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.186.0/build/three.module.js';
import {body,collide,barrier,SPECS} from './physics.mjs';
import {createEnvironment} from './environment.mjs';
const $=id=>document.getElementById(id),keys=new Set(),scene=new THREE.Scene();

const renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const camera=new THREE.PerspectiveCamera(58,1,.1,1800);scene.add(new THREE.HemisphereLight('#d2efff','#73824a',2.1));
const sun=new THREE.DirectionalLight('#fff0ce',3.4);sun.position.set(55,85,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-35,right:35,top:70,bottom:-70,near:1,far:200});sun.shadow.bias=-.0003;scene.add(sun);scene.add(sun.target);
const materials=new Map();function mat(color,metal=.1,emissive=false){const key=color+':'+metal+':'+emissive;if(!materials.has(key))materials.set(key,new THREE.MeshStandardMaterial({color,metalness:metal,roughness:metal>.3?.28:.72,...(emissive?{emissive:color,emissiveIntensity:1.8}:{})}));return materials.get(key);}
const boxGeo=new THREE.BoxGeometry(1,1,1);
function box(parent,w,h,d,x,y,z,color,metal=.1,glow=false){const mesh=new THREE.Mesh(boxGeo,mat(color,metal,glow));mesh.scale.set(w,h,d);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
const wheelGeo=new THREE.CylinderGeometry(.42,.42,.25,12);wheelGeo.rotateZ(Math.PI/2);
function model(type,color){const g=new THREE.Group(),wheels=[];
 function part(w,h,d,x,y,z,c=color,m=.5){return box(g,w,h,d,x,y,z,c,m);}
 function wheel(x,z,r=1){const tire=new THREE.Mesh(wheelGeo,mat('#121d25'));tire.position.set(x,.42*r,z);tire.scale.set(1,r,r);g.add(tire);tire.castShadow=true;wheels.push(tire);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.23*r,.23*r,.27,8),mat('#97aaa9',.8));hub.rotation.z=Math.PI/2;hub.position.copy(tire.position);g.add(hub);}
 if(type==='car'){
 part(1.88,.55,4.35,0,.68,0);part(1.62,.18,4.1,0,1.02,0);part(1.44,.6,1.95,0,1.3,-.15,'#173849',.65);part(1.5,.1,1.62,0,1.63,-.05);part(1.8,.14,.4,0,1.04,1.85,'#263944');part(1.92,.12,.3,0,1.34,-1.8);for(const x of [-.94,.94])for(const z of [-1.35,1.3])wheel(x,z);for(const x of [-.59,.59]){box(g,.53,.11,.06,x,.93,-2.2,'#ff6655',.2,true);box(g,.53,.1,.07,x,.94,2.2,'#d9fff4',.2,true);}part(.9,.18,.06,0,.62,-2.21,'#13222d');
 }else if(type==='truck'){
 part(2.25,.35,7.7,0,.8,0,'#273947');part(2.4,2.45,5.3,0,2.25,-1.2,'#e2dfcd');part(2.43,.12,5.32,0,3.52,-1.2);part(2.3,1.9,2.15,0,1.85,2.7);part(2.1,.72,.05,0,2.36,3.79,'#183746');part(2.2,.25,.1,0,1.25,3.81,'#cfebd7');for(const x of [-1.15,1.15])for(const z of [-2.8,-1.6,2.75])wheel(x,z,1.2);for(const x of [-.55,.55])part(.035,2.1,.035,x,2.28,-3.86,'#75888d');for(const x of [-1.22,1.22])part(.04,.2,4.8,x,1.65,-1.2,color);for(const x of [-.9,.9])box(g,.32,.17,.06,x,1,-3.88,'#ff7057',.1,true);
 }else if(type==='bus'){
 part(2.48,2.7,9.9,0,1.9,0);part(2.3,.18,9.3,0,3.34,0,'#d5e5d9');part(2.52,1.07,8.55,0,2.4,.05,'#173b4b');part(2.1,1,.05,0,2.5,4.97,'#204854');part(2.1,.88,.05,0,2.5,-4.97,'#204854');for(const z of [-3.8,-2.3,-.8,.7,2.2,3.7])part(2.56,1.15,.09,0,2.42,z);part(2.54,.22,9.7,0,1.3,0,'#dff6ae');for(const x of [-1.22,1.22])for(const z of [-3.25,3.15])wheel(x,z,1.17);for(const x of [-1,1])box(g,.17,.47,.06,x,1.25,-5,'#ff6c52',.1,true);box(g,1,.18,.07,0,3,-5,'#dff6ae',.1,true);
 }else{
 wheel(0,-.78,.85);wheel(0,.8,.85);part(.28,.28,1.45,0,.65,0,'#323f49');part(.55,.45,.9,0,1,.16);part(.42,.17,.75,0,1.17,-.48,'#17232d');part(.58,.54,.3,0,1.13,.75);part(.62,.1,.1,0,1.35,.64,'#bed1d1');part(.38,.55,.4,0,1.52,-.15,'#25323b');const helmet=new THREE.Mesh(new THREE.SphereGeometry(.25,12,8),mat('#eff2db',.4));helmet.position.set(0,1.98,-.04);g.add(helmet);part(.36,.12,.12,0,1.99,.18,'#173545');for(const x of [-.25,.25]){const leg=part(.18,.61,.22,x,.98,-.25,'#263847');leg.rotation.x=-.4;const arm=part(.13,.52,.15,x,1.5,.19,'#263847');arm.rotation.x=.7;}box(g,.25,.12,.08,0,1,-1.07,'#ff7057',.1,true);box(g,.26,.13,.1,0,1.3,.96,'#e2fff2',.1,true);
 }g.userData.wheels=wheels;return g;
}
// Floating render origin; collision bodies remain in world metres.
const road=new THREE.Group();scene.add(road);box(road,14,.45,1400,0,-.25,540,'#344550');
for(const x of [-7.15,7.15]){box(road,.2,.52,1400,x,.26,540,'#c5cbbd');box(road,.24,.07,1400,x,.55,540,'#edf1dc',.35);}
const markers=[];for(let z=-60;z<1050;z+=12)for(const x of [-2.3,2.3])markers.push(box(road,.1,.02,5,x,.012,z,'#c8d7d1'));
const lamps=[];for(let z=-30;z<700;z+=32)for(const side of [-1,1]){const g=new THREE.Group();g.position.set(side*7.7,0,z);box(g,.13,7,.13,0,3.5,0,'#547480');box(g,2,.1,.18,-side*.9,7,0,'#d3ffe8',.1,true);scene.add(g);lamps.push(g);}
let seed=41;function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const environment=createEnvironment(scene,renderer);
let player,playerModel,traffic=[],selected='car',mode='attract',boost=100,elapsed=0,lapTime=0,lap=1,lapProgress=0,clock=0,noticeTime=0,hitCooldown=0,last=0,accumulator=0,shake=0,soundOn=false,audio,osc,gain;
let best=Infinity;try{best=Number(localStorage.getItem('alpine-best-3d'))||Infinity;}catch{}
const colors=['#d9efb5','#edac79','#8cbbcb','#e6e9e2'];
function removeModel(m){scene.remove(m);m.traverse(o=>{if(o.isMesh&&o.geometry!==boxGeo&&o.geometry!==wheelGeo)o.geometry.dispose();});}
function reset(){if(playerModel)removeModel(playerModel);for(const t of traffic)removeModel(t.model);player=body(selected,0,0);playerModel=model(selected,'#d6edaf');scene.add(playerModel);traffic=Array.from({length:22},(_,i)=>{const type=['truck','bike','car','bus'][i%4],t=body(type,[-4.5,0,4.5][i%3],30+i*37);t.cruise=type==='bike'?32:type==='car'?27:18;t.vz=t.cruise;t.lane=t.x;t.model=model(type,colors[i%4]);scene.add(t.model);return t;});boost=100;elapsed=0;lapTime=0;lap=1;lapProgress=0;shake=0;accumulator=0;keys.clear();}
reset();
const chooser=document.createElement('div');chooser.className='vehicle-chooser';chooser.setAttribute('aria-label','Choose your vehicle');for(const type of Object.keys(SPECS)){const b=document.createElement('button');b.textContent=type.toUpperCase();b.dataset.vehicle=type;b.setAttribute('aria-pressed',String(type===selected));b.onclick=()=>{selected=type;chooser.querySelectorAll('button').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.vehicle===type)));reset();};chooser.append(b);}$('start').before(chooser);
const impactHud=document.createElement('div');impactHud.className='impact-hud';impactHud.innerHTML='<span>3D / COLLISION PHYSICS</span><b id="impact-status">ALL SYSTEMS READY</b>';$('speed-ticks').after(impactHud);
const ticks=Array.from({length:34},()=>{const e=document.createElement('i');$('speed-ticks').append(e);return e;});
const sparks=[],sparkGeo=new THREE.SphereGeometry(.05,4,3);for(let i=0;i<32;i++){const m=new THREE.Mesh(sparkGeo,mat('#ffc879',.1,true));m.visible=false;scene.add(m);sparks.push({mesh:m,life:0,v:new THREE.Vector3(),z:0});}
function impact(hit){if(hit.strength<1)return;shake=Math.max(shake,Math.min(.55,hit.strength*.022));if(hitCooldown<=0){notice(hit.strength>15?'HEAVY IMPACT':'CONTACT');hitCooldown=.7;}for(let i=0;i<12;i++){const s=sparks.find(p=>p.life<=0);if(!s)break;s.life=.3+random()*.4;s.mesh.visible=true;s.mesh.position.set(hit.x,.6,hit.z-player.z);s.z=hit.z;s.v.set((random()-.5)*9,random()*7,(random()-.5)*9);}}
function notice(msg){$('notice').textContent=msg;noticeTime=2;}
function start(){document.activeElement?.blur();reset();mode='playing';$('intro').inert=true;$('game').classList.add('playing');$('pause-modal').hidden=true;notice('THE SKYWAY IS YOURS');}
function pause(){document.activeElement?.blur();if(mode==='attract'||mode==='finished')return;keys.clear();if(mode==='playing'){mode='paused';$('modal-title').textContent='Above it all.';$('modal-copy').textContent='Your mountain escape will be right here.';$('resume').innerHTML='BACK TO THE ROAD <span>↗</span>';$('pause-modal').hidden=false;}else{mode='playing';$('pause-modal').hidden=true;}}
function simulate(dt){const throttle=keys.has('KeyW')||keys.has('ArrowUp'),brake=keys.has('KeyS')||keys.has('ArrowDown'),turn=Number(keys.has('KeyA')||keys.has('ArrowLeft'))-Number(keys.has('KeyD')||keys.has('ArrowRight')),nitro=keys.has('Space')&&boost>0&&player.vz>16&&!brake;
 const cap=player.max*(nitro?1.22:1);player.vz+=((throttle?player.accel:0)+(nitro?11:0)-(brake?25:1.6+player.vz*.014))*dt;if(player.vz>cap)player.vz=Math.max(cap,player.vz-15*dt);player.vz=Math.max(0,player.vz);const target=turn*Math.min(7,player.vz*.16)*(selected==='bike'?1.2:selected==='car'?1:.66);player.vx+=(target-player.vx)*(1-Math.exp(-player.grip*dt));boost=THREE.MathUtils.clamp(boost+(nitro?-26:8)*dt,0,100);
 const before=player.z,bodies=[player,...traffic];for(const t of traffic){const ahead=bodies.some(b=>b!==t&&Math.abs(b.x-t.x)<(b.width+t.width)/2+.2&&b.z>t.z&&b.z-t.z<(b.length+t.length)/2+9);t.vz+=(ahead?-12:THREE.MathUtils.clamp(t.cruise-t.vz,-3,2))*dt;t.vz=Math.max(0,t.vz);t.vx+=((t.lane-t.x)*1.5-t.vx)*dt*.6;}
 for(const b of bodies){b.x+=b.vx*dt;b.z+=b.vz*dt;b.impact=Math.max(0,b.impact-dt*1.8);const hit=barrier(b);if(b===player&&hit>1)impact({strength:hit,x:b.x+Math.sign(b.x)*b.width/2,z:b.z});}
 for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){const hit=collide(bodies[i],bodies[j]);if(hit&&i===0)impact(hit);}for(const b of bodies)barrier(b);
 lapProgress+=Math.max(0,player.z-before);elapsed+=dt;lapTime+=dt;hitCooldown-=dt;for(const t of traffic)if(t.z<player.z-40||t.z>player.z+1050){t.z=player.z+820+random()*120;t.x=t.lane;t.vz=t.cruise;t.vx=0;}
 if(lapProgress>=6400){lapProgress-=6400;if(lapTime<best){best=lapTime;try{localStorage.setItem('alpine-best-3d',best);}catch{}}lapTime=0;if(lap===3){mode='finished';keys.clear();$('modal-title').textContent='A higher standard.';$('modal-copy').textContent=`Three laps complete in ${Math.floor(elapsed/60)}m ${Math.floor(elapsed%60)}s.`;$('resume').innerHTML='DRIVE AGAIN <span>↗</span>';$('pause-modal').hidden=false;}else{lap++;notice('LAP '+lap+' · KEEP CLIMBING');}}
}
function format(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}<span>.${String(Math.floor(t*100)%100).padStart(2,'0')}</span>`;}
let hudClock=0;function hud(dt){hudClock+=dt;if(hudClock<.08)return;hudClock=0;const speed=Math.max(0,player.vz*3.6);$('speed').textContent=String(Math.round(speed)).padStart(3,'0');$('gear').textContent=speed<1?'N':Math.min(6,1+Math.floor(speed/52));$('time').innerHTML=format(elapsed);$('lap').innerHTML=`${String(lap).padStart(2,'0')}<span> / 03</span>`;$('best').innerHTML=best<Infinity?format(best):'— —<span> . —</span>';$('boost-fill').style.width=boost+'%';$('boost-value').textContent=Math.round(boost)+'%';ticks.forEach((e,i)=>e.classList.toggle('on',i/34<speed/340));$('drive-mode').textContent=selected.toUpperCase()+' / '+(mode==='playing'?'LIVE DRIVE':'READY TO EXPLORE');$('impact-status').textContent=player.impact>.1?'IMPACT · RECOVERING':'TRACTION CONTROL ACTIVE';$('pause').setAttribute('aria-label',mode==='paused'?'Resume game':'Pause game');const path=document.querySelector('.map-line'),pt=path.getPointAtLength(lapProgress/6400*path.getTotalLength());$('map-dot').setAttribute('cx',pt.x);$('map-dot').setAttribute('cy',pt.y);}
function render(dt){if(mode==='paused')return;const z=player.z;for(let i=0;i<markers.length;i++)markers[i].position.z=-60+Math.floor(i/2)*12-z%12;for(let i=0;i<lamps.length;i++)lamps[i].position.z=-30+Math.floor(i/2)*32-z%32;environment.update(z,clock);
 const show=(b,m)=>{m.position.set(b.x,0,b.z-z);m.rotation.y=Math.atan2(b.vx,Math.max(15,b.vz))*.6;m.rotation.z=b.type==='bike'?-b.vx*.045:-b.vx*.012;m.rotation.x=Math.sin(clock*42)*b.impact*.05;for(const wheel of m.userData.wheels)wheel.rotation.x+=b.vz*dt/.42;};show(player,playerModel);traffic.forEach(t=>show(t,t.model));for(const s of sparks){if(s.life<=0)continue;s.life-=dt;s.z+=s.v.z*dt;s.mesh.position.x+=s.v.x*dt;s.mesh.position.y+=s.v.y*dt;s.v.y-=18*dt;s.mesh.position.z=s.z-z;s.mesh.visible=s.life>0;}
 const large=selected==='bus'||selected==='truck',wanted=new THREE.Vector3(player.x*.65,large?7:4.8,large?-18:-11);camera.position.lerp(wanted,1-Math.exp(-dt*5));if(shake>.01){camera.position.x+=(random()-.5)*shake;camera.position.y+=(random()-.5)*shake;}shake*=Math.exp(-dt*7);camera.lookAt(player.x*.55,1.4,23);camera.fov=58+Math.min(7,player.vz/15);camera.updateProjectionMatrix();sun.position.x=player.x+55;sun.target.position.set(player.x,0,15);renderer.render(scene,camera);
}
function resize(){const w=innerWidth,h=Math.max(innerHeight,w<=600?700:680);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();camera.position.set(0,5,-11);
$('start').onclick=start;$('pause').onclick=()=>mode==='attract'?start():pause();$('resume').onclick=()=>mode==='finished'?start():pause();$('restart').textContent='CHANGE VEHICLE / RESTART';$('restart').onclick=()=>{mode='attract';reset();$('intro').inert=false;$('game').classList.remove('playing');$('pause-modal').hidden=true;};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat)pause();if(mode==='attract'&&['KeyW','ArrowUp'].includes(e.code))start();keys.add(e.code);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(mode==='playing')pause();});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(mode==='attract')start();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));});
$('sound').onclick=()=>{soundOn=!soundOn;if(soundOn&&!audio){audio=new(window.AudioContext||window.webkitAudioContext)();osc=audio.createOscillator();gain=audio.createGain();const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=300;osc.type='sawtooth';osc.connect(filter);filter.connect(gain);gain.connect(audio.destination);gain.gain.value=0;osc.start();}audio?.resume();$('sound').innerHTML=`♫ <span>SOUND ${soundOn?'ON':'OFF'}</span>`;$('sound').setAttribute('aria-label',soundOn?'Mute engine sound':'Enable engine sound');};
function frame(now){const dt=Math.min((now-last)/1000||0,.1);last=now;clock+=dt;if(mode==='playing'){accumulator+=dt;while(accumulator>=1/120&&mode==='playing'){simulate(1/120);accumulator-=1/120;}}else accumulator=0;if(noticeTime>0){noticeTime-=dt;if(noticeTime<=0)$('notice').textContent='';}if(audio){gain.gain.setTargetAtTime(soundOn&&mode==='playing'?.016+player.vz*.0002:0,audio.currentTime,.1);osc.frequency.setTargetAtTime(35+player.vz*2.4,audio.currentTime,.1);}render(mode==='paused'?0:dt);hud(dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
